[package]
name = "macros"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["proc-macro"]

[dependencies]
syn = { version = "2.0.13", features = ["full"] }
derive-syn-parse = "0.1.5"
quote = "1.0.26"
proc-macro2 = "1.0.56"
convert_case = "0.6.0"